### ISSUE TITLE
ETW luac file docompiling

### ISSUE THREAD

**Issue by Matwey89** [taw/etwng#4]
Good afternoon.
I have 2 questions about this - https://github.com/taw/etwng/tree/master/luac
1. I try to compile luadec on Ubunty 16.04. When I try to execute Ruby script build_luadec I have an error - 
"
../lua-5.1.4/src/liblua.a(lvm.o): In function `Arith':
lvm.c:(.text+0x34b): undefined reference to `pow'
../lua-5.1.4/src/liblua.a(lvm.o): In function `luaV_execute':
lvm.c:(.text+0x1f3a): undefined reference to `pow'
../lua-5.1.4/src/liblua.a(lcode.o): In function `codearith':
lcode.c:(.text+0x10db): undefined reference to `pow'
collect2: error: ld returned 1 exit status
[luadec.zip](https://github.com/taw/etwng/files/706756/luadec.zip)

"
Please, see build_luadec_UNsuccessful.txt log file in attachment.

If I change string - system "gcc #{cflags} -lm *.o ../lua-5.1.4/src/liblua.a -o ../../luadec"
to - system "gcc #{cflags} *.o ../lua-5.1.4/src/liblua.a -o ../../luadec -lm"

luadec build successfully - Please, see build_luadec_Successful.txt log file in attachment.

2. May be this question depends on the first question...
I try to decompil .luac like this - ./luadec -dis xxx.luac >xxx.lua
Ok, xxx.lua created. But xxx.lua file doesn't look like .lua script... 

Attach xxx.luac and xxx.lua

Am I doing something wrong? Please, can You help me?

**Comment by taw** [comment]
Order of `-lm` matters now? That's surprising. I can change this, but it's supposed to not matter.

If you use `-dis` you get lua vm code, not lua as such. That's sometimes best we can do.

**Comment by Matwey89** [comment]
Can I get "clear" lua script from xxx.luac or xxx.lua?

**Comment by taw** [comment]
OK, I updated build instructions on OSX (which became 64bit since I wrote this) and Linux (moving that `-lm` around as you said, and adding extra `apt-get` package).

Sadly `./luadec xxx.luac` segfaults on both architectures.

This isn't terribly surprising as what we have here is just somewhat patched version of decompiler for older version of lua, and trying to use it on newer version.

It can deal with most simple luac files, but not the most complex ones, and I don't think there's terribly much interest in writing a better one (especially since afaik newer Total War games no longer use lua anyway).

You can still get VM disassembly (`./luadec -dis xxx.luac`), which is of some use. 

So no, you're not doing anything wrong, this tool is just of fairly limited use.

**Comment by Matwey89** [comment]
Thank you for detailed answers!
I'm noob in ruby, so it was very interesting :)
For Windows I find another tool for ETW luac decompiling - unluac.jar

**Comment by taw** [comment]
Well, the only bit of ruby in this is the build script.

Did unluac.jar work better? There wasn't any good decompiler back then, but I haven't checked in years.

**Comment by Matwey89** [comment]
Yes, a bit of ruby, but for first step it's good:)
Unluac.jar worked correct, it decompil luac in "clear" script

**Comment by taw** [comment]
I tested both, and I just changed README to tell people to use unluac.jar

I also included it here, as sourceforge is somewhat dodgy.
